### ISSUE TITLE
Black and White to Color

### ISSUE THREAD

**Issue by pulpxi** [EntroPi-Games/GPU-Line-of-Sight#3]

**Comment by EntroPiGames** [comment]
Yes, you can replace the default desaturate image effect that's between the _LOS Buffer Storage_ and _LOS Mask_ components with any other image effect or a post processing stack to customize the way the area outside of the line of sight looks.

Please refer to section 2.1.1 of the [documentation](https://github.com/EntroPi-Games/GPU-Line-of-Sight/blob/master/Assets/EntroPi/GPU%20Line%20Of%20Sight/Documentation/Manual%20v1.4.pdf) for more info.
